// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_W5fjD0HHYESGF8_T9Au2DEhdC8qTH98',
    appId: '1:254395731354:web:dac1f7d293a3d3f29e7e23',
    messagingSenderId: '254395731354',
    projectId: 'lab10-3e1a6',
    authDomain: 'lab10-3e1a6.firebaseapp.com',
    storageBucket: 'lab10-3e1a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE5ggpLjCYFfQbffuVkgaRhD1heZnUJhk',
    appId: '1:254395731354:android:d0e53a58c79c3f809e7e23',
    messagingSenderId: '254395731354',
    projectId: 'lab10-3e1a6',
    storageBucket: 'lab10-3e1a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvf18kNYkHDj7CRk22laanbxVuVygEHEs',
    appId: '1:254395731354:ios:ef028d61799e42489e7e23',
    messagingSenderId: '254395731354',
    projectId: 'lab10-3e1a6',
    storageBucket: 'lab10-3e1a6.appspot.com',
    iosClientId: '254395731354-k7u1vstnhltknqdrscepft01eiligmiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvf18kNYkHDj7CRk22laanbxVuVygEHEs',
    appId: '1:254395731354:ios:ef028d61799e42489e7e23',
    messagingSenderId: '254395731354',
    projectId: 'lab10-3e1a6',
    storageBucket: 'lab10-3e1a6.appspot.com',
    iosClientId: '254395731354-k7u1vstnhltknqdrscepft01eiligmiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab10',
  );
}
